# Numpy Broadcastig


In [2]:
import numpy as np
A = np.array([[56.0,0.0,4.4,68.0],
              [1.2,104.0,52.0,8.0],
              [1.8,135.0,99.0,0.9]])
A.T

array([[ 56. ,   1.2,   1.8],
       [  0. , 104. , 135. ],
       [  4.4,  52. ,  99. ],
       [ 68. ,   8. ,   0.9]])

### Broadcasting occured in this operation
` percentage =  100*A/Cal.reshape(1,4)`

In [3]:
Cal = A.sum(axis=0) #axis 0 is row sum 
percentage =  100*A/Cal.reshape(1,4)  #reshape is just to be explicit
percentage

array([[94.91525424,  0.        ,  2.83140283, 88.42652796],
       [ 2.03389831, 43.51464435, 33.46203346, 10.40312094],
       [ 3.05084746, 56.48535565, 63.70656371,  1.17035111]])

### Other example of broadcasting
Adding a `s` scalar to a matrix `A`, where the scalar is broadcasted to all components of the matrix

In [6]:
b = 5
B =  A + b
B-A

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

## General Rule 
* Matrix `(m,n)  +-*/ (1,n)` -> broadcasted as `(m,n)` and operated element-wise
* Matrix `(m,n)  +-*/ (m,1)` -> broadcasted as `(m,n)` and operated element-wise
