In [107]:
import numpy as np

$$A \in\mathbb{R}^{n\times m}$$

In [47]:
a= np.array([1,2,3,4]).reshape(4,1) #remember to reshape to be explicit with the dimensions
print(type(a))
print(a.shape)

<class 'numpy.ndarray'>
(4, 1)


### Indexing elements
Indexes start from zero

* `a[i][j]` or `a[i,j]` where i: row index and j: column index
* `a[:,j]` get column j 
* `a[i,:]` get row j


In [79]:
print(a[0][0])
print(a[1][0])
print(a[2][0])
print(a[3][0])
print(a[0:3].T)  # from zero to 3 excluding 3

1
2
3
4
[[1 2 3]]


In [89]:
b = np.random.randn(3,3)
print(b)
print(b.shape)
print(b[2,2])
print(b[:,2]) #get column 2
print(b[2,:]) #get row 2

[[-3.73784448e-01  6.13746378e-01 -4.51442986e-01]
 [-9.70245230e-04 -9.50386592e-01  1.83060232e+00]
 [ 5.31191312e-02 -4.76788419e-01  6.43895896e-01]]
(3, 3)
0.6438958959648515
[-0.45144299  1.83060232  0.6438959 ]
[ 0.05311913 -0.47678842  0.6438959 ]


### Modify elements of an array

In [94]:
b[1,1] = 5000
print(b)

[[-3.73784448e-01  6.13746378e-01 -4.51442986e-01]
 [-9.70245230e-04  5.00000000e+03  1.83060232e+00]
 [ 5.31191312e-02 -4.76788419e-01  6.43895896e-01]]


### Special Default matrices
* Indentity matrix : `np.eye(m,n)`
* Zero matrix      : `np.zeros((m,n))`
* Ones Matrix      : `np.ones((m,n))`
* Fill Matrix      : `np.full((m,n), val, dtype= type)`

In [102]:
I = np.eye(3,3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [99]:
Z = np.zeros((3,3))
print(Z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [104]:
Ones = np.ones((3,3))
print(Ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [108]:
C = np.full((3,3),5)
print(C)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


### Random array and computing mean and std

In [157]:
R = np.random.randn(3,3)
print(R)
print(np.mean(R))
print(np.std(R))

[[ 0.22010524 -0.39871654  0.38670938]
 [ 1.12802231 -2.43284873 -1.07960891]
 [-0.88544058  0.08957221 -0.62504082]]
-0.39969404910226713
0.969456564824154


In [161]:
print(np.mean(R, axis=1))  #specify the axis to compute the mean and std
print(np.std(R,axis=1))

[ 0.06936603 -0.79481178 -0.4736364 ]
[0.33790058 1.46760183 0.41219329]


### Array dtype
* `a.dtype`

In [165]:
print(R.dtype)
print(a.dtype)

float64
int64


# Matrix Operations
* `A+B` or `np.add(A,B, dtype = int)`, the advanatge of using the last method is that the datatype can be defined
* `A-B` or `np.sustract(A,B, dtype = int)`

In [174]:
A = np.full((3,3),4,dtype=int)
B = np.full((3,3),2)
#Addition
A + B
np.add(A,B, dtype=float)
#substraction
A-B
np.subtract(A,B, dtype = int)

[[6 6 6]
 [6 6 6]
 [6 6 6]]
[[6. 6. 6.]
 [6. 6. 6.]
 [6. 6. 6.]]


array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])