# Matrix Operations

In [10]:
import numpy as np
A = np.random.randn(3,3)
B = np.random.randn(3,3)
print(A)
print(B)

[[-0.47353891 -0.29147089  1.26990881]
 [ 0.77153763  1.42715284 -1.30124337]
 [-0.07690577  0.56552192 -0.59523099]]
[[ 0.19587713  0.30817735  1.08664414]
 [-1.83295342  1.34652823 -1.08791685]
 [ 0.23440662 -2.37664407 -0.40149488]]


### Pointwise Multiplication and Division:
* `C = A*B` or `np.multiply(A,B,dtype =type)`
* `C = A/B` or `np.divide(A,B,dtype=type)`
    

In [19]:
C = A*B
C1 = np.multiply(A,B,dtype = np.float16)
C-C1

array([[ 1.79950693e-05,  1.90229627e-05,  5.61616831e-05],
       [-1.30035995e-04,  8.03156041e-04,  6.05518080e-04],
       [-6.59173333e-06, -2.94320356e-04, -3.14743896e-05]])

In [15]:
C = A/B
C1 = np.divide(A,B)
C-C1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### Matrix Multiplication
* `np.matmul(A,B)`
$$C= AB$$
where $A\in\mathbb{R}^{M\times N}, B\in\mathbb{R}^{N\times M}$ the product is defined as
$$C_{i,j} = \sum_{k=1}^N A_{i,k}B_{k,j}$$

In [91]:
A = np.array([[3,8],
              [-1,4]])
B = np.array([[4,5],
              [6,7]])

In [85]:
np.matmul(A,B)

array([[60, 71],
       [28, 33]])

### Dot Product
* `np.dot(A,B)` or `np.inner(A,B)`
$$<a,b> = a^Tb=\sum_{i=1}^na_ib_i$$

In [86]:
np.dot(A,B)

array([[60, 71],
       [28, 33]])

In [87]:
np.inner(A,B.T)

array([[60, 71],
       [28, 33]])

In [88]:
a = np.array([1,2,3]).reshape(3,1)
b = np.array([1,2,3]).reshape(1,3)
print(np.dot(a,b))
print(np.dot(b,a))
print(np.inner(a.T,b))

[[1 2 3]
 [2 4 6]
 [3 6 9]]
[[14]]
[[14]]


### Matrix Power
* `np.linalg.matrix_power(A,n)`
$$A^n= A\cdot A\cdots A$$

### Kronecher Product
* `np.kron(A,B)`
$$A\otimes B$$

In [89]:
np.kron(A,B)

array([[12, 15, 32, 40],
       [18, 21, 48, 56],
       [ 4,  5, 16, 20],
       [ 6,  7, 24, 28]])

# Matrix Decompositions

## Cholesky Decomposition
* `np.linalg.cholesky(A)`
$$A = UU^H$$

In [102]:
np.linalg.cholesky(np.dot(B.T,B))

array([[7.21110255, 0.        ],
       [8.59785304, 0.2773501 ]])

In [114]:
A = np.array([[3,8],
              [-1,4]])
A = np.dot(A.T,A)
print(A)

[[10 20]
 [20 80]]


In [105]:
np.linalg.eigvals(A)

array([ 4.68871126, 85.31128874])

In [107]:
np.linalg.cond(A)

18.19503996683587

In [109]:
np.linalg.det(A)

399.9999999999999

In [112]:
np.linalg.matrix_rank(A)

2

In [120]:
np.trace(A)

90

## Solving linear equations of the form
$$Ax = b$$
* `np.linalg.solve(A,b)`
* `np.linalg.inv(A) dot b` :  $x = A^{-1}b$
* `np.linalg.pinv(A) dot b`:  $x = A^{+}b$    with pseudoinverse pinv

In [118]:
b = np.array([1,2])
np.linalg.solve(A,b)

array([ 0.1, -0. ])

In [121]:
np.dot(np.linalg.inv(A),b)

array([0.1, 0. ])

In [122]:
np.dot(np.linalg.pinv(A),b)

array([ 1.0000000e-01, -6.9388939e-18])