In [13]:
import numpy as np
array = np.array([[1,1,1],[2,3,5],[1,1,1]])
array

array([[1, 1, 1],
       [2, 3, 5],
       [1, 1, 1]])

In [14]:
array.shape

(3, 3)

In [15]:
array.sum()

16

In [19]:
(array>1)

array([[False, False, False],
       [ True,  True,  True],
       [False, False, False]])

In [21]:
np.amax(array)

5

In [27]:
np.amax(array, axis =0)

array([2, 3, 5])

In [32]:
np.argmax(array, axis=None)

5

In [37]:
np.unravel_index(np.argmax(array,axis=None), array.shape)

(1, 2)

In [40]:
array[1][2]

5