In [22]:
import numpy as np
a = np.random.randn(5)


## Transpose of a numpy vector:
* `a.T`


In [24]:
print(a.T)
print(a.shape)

[ 0.14840318 -1.04547869  0.54938647  0.87069794  1.13557367]
(5,)


### Be explicit with the definitions of the vectors to avoid dimensions issues
note that the previous vector `a` has a shape (5,) that is not clear if it is a column or row vector

In [25]:
print(np.dot(a,a.T))
print(np.dot(a.T,a))

3.4645171407612727
3.4645171407612727


Note that the prevous result throughs the same result for both operations, where in the first case should have been a 5x5 matrix and the second case a scalar

Try this better:

In [26]:
a = a.reshape(5,1)
print("5x5 Matrix:")
print(np.dot(a,a.T))
print("scalar (1x1 matrix):")
print(np.dot(a.T,a))

5x5 Matrix:
[[ 0.0220235  -0.15515236  0.0815307   0.12921434  0.16852274]
 [-0.15515236  1.09302569 -0.57437184 -0.91029614 -1.18721807]
 [ 0.0815307  -0.57437184  0.30182549  0.47834966  0.6238688 ]
 [ 0.12921434 -0.91029614  0.47834966  0.7581149   0.98874166]
 [ 0.16852274 -1.18721807  0.6238688   0.98874166  1.28952756]]
scalar (1x1 matrix):
[[3.46451714]]
